### ISSUE TITLE
java.lang.Throwable: method not implemented in class com.intellij.psi.impl.file.PsiPackageImpl

### ISSUE THREAD

**Issue by danny-su** [alezhu/intellij_named_argument_stubs_plugin#2]
java.lang.Throwable: method not implemented in class com.intellij.psi.impl.file.PsiPackageImpl
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.psi.impl.file.PsiPackageBase.getChildren(PsiPackageBase.java:117)
	at com.intellij.psi.impl.PsiElementBase.getFirstChild(PsiElementBase.java:33)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:37)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:19)
	at com.intellij.util.WalkingState.next(WalkingState.java:70)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:49)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:40)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:67)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:34)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:940)
	at com.intellij.psi.impl.file.PsiPackageImpl.accept(PsiPackageImpl.java:118)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:936)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:233)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:199)
	at ru.alezhu.idea.plugins.named_argument_stubs.Context$parameterList$2.invoke(Context.kt:46)
	at ru.alezhu.idea.plugins.named_argument_stubs.Context$parameterList$2.invoke(Context.kt:44)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at ru.alezhu.idea.plugins.named_argument_stubs.Context.getParameterList(Context.kt:44)
	at ru.alezhu.idea.plugins.named_argument_stubs.Context.isAvailable(Context.kt:69)
	at ru.alezhu.idea.plugins.named_argument_stubs.NamedArgumentStubsIntention.isAvailable(NamedArgumentStubsIntention.kt:23)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:205)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getRegisteredIntentionActions$6(ShowIntentionsPass.java:376)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:275)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getRegisteredIntentionActions(ShowIntentionsPass.java:375)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:347)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:250)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:426)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:417)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:416)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:392)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:392)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:390)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:259)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

**Comment by alezhu** [comment]
@danny-su  Which IDE? Version? Source code? Position in it on which intension was called?

**Comment by danny-su** [comment]
@alezhu 不记得什么页面了，好像是打开gradle的脚本的时候。
<img width="482" alt="image" src="https://github.com/user-attachments/assets/b457d666-d672-44f0-ae11-45e2d5cf7da4">
